(self.AMP=self.AMP||[]).push({n:"amp-auto-lightbox",v:"1903281741200",f:(function(AMP,_){
(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a})(this);function h(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function k(a){return new Promise(function(b){b(a())})};function l(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var m=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function n(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var p=self.log;function q(){if(p.dev)return p.dev;throw Error("failed to call initLogConstructor");};function t(a,b){var c,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(u(d,b)){var f=v(d,b);if(f)return f}if(!c)return null}a=w(a);a=x(a);return u(a,b)?v(a,b):null}function y(a,b){a=a.__AMP_TOP||a;return v(a,b)}function w(a){return a.nodeType?y((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function x(a){a=w(a);return a.isSingleDoc()?a.win:a}
function v(a,b){u(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function u(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function z(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function A(a){return a.closest?a.closest("a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option]"):z(a,function(a){return B(a,"a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option]")})}
function B(a,b){var c=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return c?c.call(a,b):!1}function C(a,b){for(var c=a.length,d=0;d<c;d++)b(a[d],d)}function D(a){if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new h;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};/nochunking=1/.test(self.location.hash);Promise.resolve();(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});function E(a){var b="amp-auto-lightbox-carousel";if(a.__AMP__EXPERIMENT_TOGGLES)var c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0)}Object.assign(c,F(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var g;g=m.exec(e);)f=l(g[1],g[1]),g=g[2]?l(g[2],g[2]):"",a[f]=g;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}var r=c;return!!r[b]}
function F(a){a:{try{var b=a.document.cookie}catch(g){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==l(c.substring(0,d).trim(),void 0)){a=c.substring(d+1).trim();a=l(a,a);break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};function G(a){if("a"==a.tagName.toLowerCase()&&a.hasAttribute("href")||a.querySelector("a[href]"))return!0;var b=t(a,"action"),c=b.hasResolvableAction(a,"tap",a.parentElement);if(c)return!0;var d=a.querySelectorAll("[on]");for(a=0;a<d.length;a++){var e=d[a];if(b.hasResolvableAction(e,"tap",e.parentElement))return!0}return!1};function H(){return k(function(){return!1})}function I(){return k(function(){return!0})};function J(a){if(!E(a.ownerDocument.defaultView))return H();var b=a.querySelectorAll(".amp-carousel-slide"),c=a.querySelectorAll("amp-img");if(1>c.length||b.length!=c.length)return H();var d=I();C(b,function(a){d=d.then(function(b){return b?K(a):!1})});return d}function K(a){if("AMP-IMG"==a.tagName)return k(function(){return!G(a)});var b=a.querySelector("amp-img");if(!b)return H();var c=L(b,a);return c.then(function(b){return b?!G(a):!1})}
function L(a,b){return a.getImpl().then(function(c){return new Promise(function(d){c.measureElement(function(){var c=a.getLayoutBox(),f=c.width,g=c.height;c=b.getBoundingClientRect();var r=c.width,O=c.height,P=f*g,Q=r*O;d(.5<=P/Q)})})})};var M={Article:!0,NewsArticle:!0,BlogPosting:!0,LiveBlogPosting:!0,DiscussionForumPosting:!0},N=["amp-img","amp-carousel"];function R(){}
function S(a){if("AMP-IMG"==a.tagName.toUpperCase()){var b=a.querySelector("img");var c=b.naturalWidth;b=b.naturalHeight;var d=a.getLayoutBox(),e=d.width;d=d.height;var f=w(a);f=x(f);var g=v(f,"viewport").getSize();f=g.width;g=g.height;e*=d;c=1.2<=c*b/e||c>f||b>g||.25<=e/(f*g)}else c=!0;c&&(c=(c=A(a))&&(c!=a||B(c,"[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option]"))?!1:!t(a,"action").hasResolvableAction(a,"tap"));return c?"AMP-CAROUSEL"==a.tagName.toUpperCase()?J(a):I():H()}
function T(a){return U(a,function(){a.setAttribute("i-amphtml-auto-lightbox-visited","")})}function V(a){return a+":not([lightbox]):not([i-amphtml-auto-lightbox-visited])"}function W(a){return D(a).then(function(a){return a.signals().whenSignal("load-end")})}function X(a){return n(a.getRootNode().querySelectorAll('script[type="application/ld+json"]')).map(function(a){var b=a.textContent;a:{try{var d=JSON.parse(b);break a}catch(e){}d=void 0}return(d||{})["@type"]}).filter(function(a){return a})}
function Y(a){return X(a).some(function(a){return M[a]})}function U(a,b){return D(a).then(function(a){return a.getResources().mutateElement(a,b)})}function aa(a){function b(b){return!!a.getRootNode().querySelector(b)}var c='script[custom-element="amp-lightbox-gallery"]',d="[lightbox]:not([i-amphtml-auto-lightbox-visited])";return b(c)&&b(d)}var ba=0;
function ca(a,b){return U(b,function(){b.setAttribute("lightbox","i-amphtml-auto-lightbox-"+ba++)}).then(function(){y(a.win,"extensions").installExtensionForDoc(a,"amp-lightbox-gallery");b.dispatchCustomEvent("amp-auto-lightbox:newly-set");return b})}function da(a,b){b.map(function(b){return W(b).then(function(){return S(b).then(function(c){if(c)return q().info("amp-auto-lightbox","apply",b),ca(a,b)})},R)})}
function Z(a,b){var c;(c=aa(a))||(c=(c=a.getRootNode().querySelector('meta[property="og:type"]'))?c.getAttribute("content"):void 0,c="article"!=c&&!Y(a));if(c)c=!1;else{c=a.win;var d=a.getBody().firstElementChild;c=d?t(d,"url").isProxyOrigin(c.location):!1}c?(c=b||a.win.document,d=N.map(V).join(","),c=n(c.querySelectorAll(d)),c.forEach(T),da(a,c)):q().info("amp-auto-lightbox","disabled")}
(function(a){var b=a.ampdoc;b.whenReady().then(function(){b.getRootNode().addEventListener("amp:dom-update",function(a){Z(b,a.target)});Z(b)})})(self.AMP);
})});
//# sourceMappingURL=amp-auto-lightbox-0.1.js.map

